-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2023-10-18 06:40:57.816

-- tables
-- Table: JENIS_LAYANAN
CREATE TABLE JENIS_LAYANAN (
    JL_ID varchar(5)  NOT NULL,
    JL_NAMA varchar(100)  NOT NULL,
    JL_HARGA numeric(6,2)  NOT NULL,
    CONSTRAINT JENIS_LAYANAN_pk PRIMARY KEY (JL_ID)
);

-- Table: JENIS_LAYANAN_NOTA
CREATE TABLE JENIS_LAYANAN_NOTA (
    JENIS_LAYANAN_JL_ID varchar(5)  NOT NULL,
    NOTA_N_NO int  NOT NULL,
    CONSTRAINT JENIS_LAYANAN_NOTA_pk PRIMARY KEY (JENIS_LAYANAN_JL_ID,NOTA_N_NO)
);

-- Table: KARYAWAN
CREATE TABLE KARYAWAN (
    K_ID char(2)  NOT NULL,
    K_NAMA varchar(100)  NOT NULL,
    K_BAGIAN varchar(25)  NULL,
    K_TGLMASUK date  NULL,
    K_EMAIL varchar(100)  NOT NULL,
    K_PASSWORD varchar(100)  NOT NULL,
    CONSTRAINT KARYAWAN_pk PRIMARY KEY (K_ID)
);

-- Table: NOTA
CREATE TABLE NOTA (
    N_NO int  NOT NULL,
    N_TGL_MASUK date  NOT NULL,
    N_TGLPERKIRAANSELESAI date  NOT NULL,
    N_TGLSELESAI date  NULL,
    N_TGLAMBIL timestamp  NULL,
    N_STATUS varchar(10)  NOT NULL,
    N_KODERAK varchar(3)  NULL,
    PELANGGAN_P_NO char(5)  NOT NULL,
    CONSTRAINT NOTA_pk PRIMARY KEY (N_NO)
);

-- Table: NOTA_KARYAWAN
CREATE TABLE NOTA_KARYAWAN (
    NOTA_N_NO int  NOT NULL,
    KARYAWAN_K_ID char(2)  NOT NULL,
    CONSTRAINT NOTA_KARYAWAN_pk PRIMARY KEY (NOTA_N_NO,KARYAWAN_K_ID)
);

-- Table: PAYMENT
CREATE TABLE PAYMENT (
    B_NO int  NOT NULL,
    B_TOTALHARGA numeric(10,2)  NOT NULL,
    B_TGLBAYAR date  NOT NULL,
    NOTA_N_NO int  NOT NULL,
    CONSTRAINT PAYMENT_pk PRIMARY KEY (B_NO)
);

-- Table: PELANGGAN
CREATE TABLE PELANGGAN (
    P_NO char(5)  NOT NULL,
    P_NAMA varchar(60)  NOT NULL,
    P_JENISKEL char(1)  NULL,
    P_TEMPATLAHIR int  NULL,
    P_TGLLAHIR date  NULL,
    P_ALAMAT varchar(100)  NULL,
    P_NOTELP varchar(15)  NULL,
    P_TGLFATTAR int  NOT NULL,
    CONSTRAINT PELANGGAN_pk PRIMARY KEY (P_NO)
);

-- foreign keys
-- Reference: JENIS_LAYANAN_NOTA_JENIS_LAYANAN (table: JENIS_LAYANAN_NOTA)
ALTER TABLE JENIS_LAYANAN_NOTA ADD CONSTRAINT JENIS_LAYANAN_NOTA_JENIS_LAYANAN FOREIGN KEY JENIS_LAYANAN_NOTA_JENIS_LAYANAN (JENIS_LAYANAN_JL_ID)
    REFERENCES JENIS_LAYANAN (JL_ID);

-- Reference: JENIS_LAYANAN_NOTA_NOTA (table: JENIS_LAYANAN_NOTA)
ALTER TABLE JENIS_LAYANAN_NOTA ADD CONSTRAINT JENIS_LAYANAN_NOTA_NOTA FOREIGN KEY JENIS_LAYANAN_NOTA_NOTA (NOTA_N_NO)
    REFERENCES NOTA (N_NO);

-- Reference: MEMASUKKAN (table: NOTA)
ALTER TABLE NOTA ADD CONSTRAINT MEMASUKKAN FOREIGN KEY MEMASUKKAN (PELANGGAN_P_NO)
    REFERENCES PELANGGAN (P_NO);

-- Reference: MENGKOORDINIR (table: KARYAWAN)
ALTER TABLE KARYAWAN ADD CONSTRAINT MENGKOORDINIR FOREIGN KEY MENGKOORDINIR (K_ID)
    REFERENCES KARYAWAN (K_ID);

-- Reference: NOTA_KARYAWAN_KARYAWAN (table: NOTA_KARYAWAN)
ALTER TABLE NOTA_KARYAWAN ADD CONSTRAINT NOTA_KARYAWAN_KARYAWAN FOREIGN KEY NOTA_KARYAWAN_KARYAWAN (KARYAWAN_K_ID)
    REFERENCES KARYAWAN (K_ID);

-- Reference: NOTA_KARYAWAN_NOTA (table: NOTA_KARYAWAN)
ALTER TABLE NOTA_KARYAWAN ADD CONSTRAINT NOTA_KARYAWAN_NOTA FOREIGN KEY NOTA_KARYAWAN_NOTA (NOTA_N_NO)
    REFERENCES NOTA (N_NO);

-- Reference: PAYMENT_NOTA (table: PAYMENT)
ALTER TABLE PAYMENT ADD CONSTRAINT PAYMENT_NOTA FOREIGN KEY PAYMENT_NOTA (NOTA_N_NO)
    REFERENCES NOTA (N_NO);

-- End of file.

